# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

platform :ios, '8.0'

target ‘MyGirl’ do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for JYHomeCloud
inhibit_all_warnings!                  #取消三方框架导致的警告

pod 'MJExtension'#, '3.0.13'
pod 'MBProgressHUD'
pod 'Masonry'                          #控件适配
pod 'YYCache'                          #缓存工具库
pod 'YYText'                           #文本工具库
pod 'YYCategories'                     #分类方法工具库
pod 'IQKeyboardManager'                #管理键盘
pod 'MJRefresh'



#use_frameworks!



end
